
// MAP RELATED
export const UPDATE_RADIUS = 'UPDATE_RADIUS'

export const UPDATE_FILTER = 'UPDATE_FILTER'


export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION'


// 
export const FETCH_SCHEDULED_VISITS = 'FETCH_SCHEDULED_VISITS'



// AXIOS_FETCH_VIDEO_LISTING 
export const AXIOS_FETCH_VIDEO_LISTING = 'AXIOS_FETCH_VIDEO_LISTING'

export const AXIOS_POST_VIDEO_LISTING = 'AXIOS_POST_VIDEO_LISTING'


// Grab user profile information from the DB/Auth0.
export const FETCH_PROFILE = 'FETCH_PROFILE'

export const STORE_PROFILE = 'STORE_PROFILE'


// Sends out the upload info object array
export const UPDATE_VIDEO_UPLOAD_INFO = 'UPDATE_VIDEO_UPLOAD_INFO'

export const UPDATE_SELECTED_VIDEO = 'UPDATE_SELECTED_VIDEO'



// TYPES RELATED TO SELECT VIDEOS 
export const SELECT_VIDEO = 'SELECT_VIDEO' 

export const SELECT_ROOMTYPE = 'SELECT_ROOMTYPE'

export const SET_VIDEO_START_TIME = 'SET_VIDEO_START_TIME'

export const SET_VIDEO_END_TIME = 'SET_VIDEO_END_TIME'

export const SEEKBAR_CURRENT_TIME = 'SEEKBAR_CURRENT_TIME'

export const UPDATE_VIDEO_SERIES_INFO = 'UPDATE_VIDEO_SERIES_INFO'

export const UPDATE_VIDEO_ORDER = 'UPDATE_VIDEO_ORDER'

export const SET_VIDEO_INFO = 'SET_VIDEO_INFO'

export const UPDATE_VIDEO_MAP_ORDER = 'UPDATE_VIDEO_MAP_ORDER'

export const CREATE_HASHTAG_MARKER = 'CREATE_HASHTAG_MARKER'

export const UPDATE_HASHTAG_MARKER = 'UPDATE_HASHTAG_MARKER'

export const DELETE_HASHTAG_MARKER = 'DELETE_HASHTAG_MARKER'

export const CHANGE_HASH_TAG_PICTURE = 'CHANGE_HASH_TAG_PICTURE'


// 




