blank_issues_enabled: false
contact_links:
  - name: Homer Community Support
    url: https://athomehack.slack.com/
    about: Please ask and answer questions here.
  - name: Homer Security Bug Collectors
    url: https://athomehack.slack.com/
    about: Please report security vulnerabilities here.
